[[tour]]
id = 0
name = "cplib"
path = "/home/peng/cplib/src/lib.rs"

[[tour]]
id = 1
parent = 0
name = "core"
path = "/home/peng/cplib/src/core/mod.rs"

[[tour]]
id = 2
parent = 1
name = "internal_macros"
path = "/home/peng/cplib/src/core/internal_macros.rs"

[[tour]]
id = 3
parent = 1
name = "binary_search"
path = "/home/peng/cplib/src/core/binary_search.rs"

[[tour]]
id = 4
parent = 1
name = "rng"
path = "/home/peng/cplib/src/core/rng.rs"

[[tour]]
id = 5
parent = 1
name = "sub_mask"
path = "/home/peng/cplib/src/core/sub_mask.rs"

[[tour]]
id = 6
parent = 1
name = "modular"
path = "/home/peng/cplib/src/core/modular.rs"

[[tour]]
id = 7
parent = 1
name = "num"
path = "/home/peng/cplib/src/core/num/mod.rs"

[[tour]]
id = 8
parent = 7
name = "float"
path = "/home/peng/cplib/src/core/num/float.rs"

[[tour]]
id = 9
parent = 7
name = "identities"
path = "/home/peng/cplib/src/core/num/identities.rs"

[[tour]]
id = 10
parent = 7
name = "integer"
path = "/home/peng/cplib/src/core/num/integer.rs"

[[tour]]
id = 11
parent = 7
name = "modulo"
path = "/home/peng/cplib/src/core/num/modulo.rs"

[[tour]]
id = 12
parent = 7
name = "number"
path = "/home/peng/cplib/src/core/num/number.rs"

[[tour]]
id = 13
parent = 0
name = "algebra"
path = "/home/peng/cplib/src/algebra/mod.rs"

[[tour]]
id = 14
parent = 13
name = "add"
path = "/home/peng/cplib/src/algebra/add.rs"

[[tour]]
id = 15
parent = 13
name = "bit"
path = "/home/peng/cplib/src/algebra/bit.rs"

[[tour]]
id = 16
parent = 13
name = "cmp"
path = "/home/peng/cplib/src/algebra/cmp.rs"

[[tour]]
id = 17
parent = 0
name = "io"
path = "/home/peng/cplib/src/io.rs"

[[tour]]
id = 18
parent = 0
name = "ds"
path = "/home/peng/cplib/src/ds/mod.rs"

[[tour]]
id = 19
parent = 18
name = "dsu"
path = "/home/peng/cplib/src/ds/dsu/mod.rs"

[[tour]]
id = 20
parent = 19
name = "basic"
path = "/home/peng/cplib/src/ds/dsu/basic.rs"

[[tour]]
id = 21
parent = 19
name = "roll_back"
path = "/home/peng/cplib/src/ds/dsu/roll_back.rs"

[[tour]]
id = 22
parent = 18
name = "fenwick"
path = "/home/peng/cplib/src/ds/fenwick/mod.rs"

[[tour]]
id = 23
parent = 22
name = "range"
path = "/home/peng/cplib/src/ds/fenwick/range.rs"

[[tour]]
id = 24
parent = 22
name = "tree"
path = "/home/peng/cplib/src/ds/fenwick/tree.rs"

[[tour]]
id = 25
parent = 18
name = "seg"
path = "/home/peng/cplib/src/ds/seg/mod.rs"

[[tour]]
id = 26
parent = 25
name = "lazy"
path = "/home/peng/cplib/src/ds/seg/lazy.rs"

[[tour]]
id = 27
parent = 25
name = "tree"
path = "/home/peng/cplib/src/ds/seg/tree.rs"

[[tour]]
id = 28
parent = 18
name = "sparse_table"
path = "/home/peng/cplib/src/ds/sparse_table.rs"

[[tour]]
id = 29
parent = 0
name = "math"
path = "/home/peng/cplib/src/math/mod.rs"

[[tour]]
id = 30
parent = 29
name = "comb"
path = "/home/peng/cplib/src/math/comb.rs"

[[tour]]
id = 31
parent = 29
name = "div_block"
path = "/home/peng/cplib/src/math/div_block.rs"

[[tour]]
id = 32
parent = 29
name = "divide"
path = "/home/peng/cplib/src/math/divide.rs"

[[tour]]
id = 33
parent = 29
name = "garner"
path = "/home/peng/cplib/src/math/garner.rs"

[[tour]]
id = 34
parent = 29
name = "prefix_boost"
path = "/home/peng/cplib/src/math/prefix_boost.rs"

[[tour]]
id = 35
parent = 29
name = "sieve"
path = "/home/peng/cplib/src/math/sieve.rs"

[[tour]]
id = 36
parent = 29
name = "subset"
path = "/home/peng/cplib/src/math/subset.rs"

[[tour]]
id = 37
parent = 0
name = "string"
path = "/home/peng/cplib/src/string/mod.rs"

[[tour]]
id = 38
parent = 37
name = "kmp"
path = "/home/peng/cplib/src/string/kmp.rs"

[[tour]]
id = 39
parent = 37
name = "manacher"
path = "/home/peng/cplib/src/string/manacher.rs"

[[tour]]
id = 40
parent = 37
name = "suffix_array"
path = "/home/peng/cplib/src/string/suffix_array.rs"

[[tour]]
id = 41
parent = 37
name = "z_fn"
path = "/home/peng/cplib/src/string/z_fn.rs"
