path = "/home/peng/cprust/src/bin/"

[components]
default = ["io"]
rmq = ["sparse_table", "algebra"]
segtree = ["algebra", "seg"]
seglazy = ["algebra", "lazy"]
m32 = ["modular", "algebra", "num"]
sa = ["suffix_array", "rmq"]
gcd = ["modulo", "num"]
boost = ["prefix_boost", "div_block", "sieve"]